---
apiVersion: v1
kind: Namespace
metadata:
  name: kpack
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnY3IuaW8iOnsiYXV0aCI6IlgycHpiMjVmYTJWNU9uc2dJblI1Y0dVaU9pQWljMlZ5ZG1salpWOWhZMk52ZFc1MElpd2dJbkJ5YjJwbFkzUmZhV1FpT2lBaVkyWXRZblZwYkdRdGMyVnlkbWxqWlMxa1pYWXRNakU1T1RFeklpd2dJbkJ5YVhaaGRHVmZhMlY1WDJsa0lqb2dJakZtWlRSaFpXWXlOR0UwWTJJMU9EUTRaVEJsWmpGbFpXVmhOV016WTJJd04yVXhPVGMxWkdFaUxDQWljSEpwZG1GMFpWOXJaWGtpT2lBaUxTMHRMUzFDUlVkSlRpQlFVa2xXUVZSRklFdEZXUzB0TFMwdFhHNU5TVWxGZGxGSlFrRkVRVTVDWjJ0eGFHdHBSemwzTUVKQlVVVkdRVUZUUTBKTFkzZG5aMU5xUVdkRlFVRnZTVUpCVVVSdGVXaFphVnBMVlhCcGMwaDJYRzVWWlhGc2RsbFNMemgyWTNNeFduWnNNVFoxZGtONmVVbElhQzkwYVZGTE1VOW5jMFV3UjBWTmRsQkNhbVJuVTJ0WmRqTXJOVUpPV21kVVpHeHhSVlozWEc1WU0wZDBNbTlTZFN0RFNucG9lRUpFUzJObFkxRlVUWHBWYkc4ek9VMDJjWEJVZUVoWFpYRlJhbUZzT0d0RGRYVkpOMEpDV0hwbFkxQnpVbEJETnpSVFhHNWxhbVl2Tm10c1UzSmFaRVJQVFRGM2JteHZTM05PWWtwWFduUlpSa3BQUkhKSVZ6RXdSakptVjFkM2RGWmpiMjlYVXpSVlozQXlZemh1TkVsck15dE5YRzVDV2pWWlpWRlhSbFYxWVVrMmFqZ3pRV2wzYmpkb1RHazROMU5ZU1hCU1dGb3pibmxyU25vd1RsWTVTV3RXV2tWblFTdHpOSEpOUnpkYVFtRktlVlo1WEc1eFdqQnFhQzl1UTNsS1puZFdNbTVGYUZVclVWbHBNVzVyVkhscVRURTRUWFZOWTNSSU1rMTNNRGhpTTB0SVZUbEdXWHAzWVhCTFkyNDFSWHBLYWxOTlhHNTJkM1ZGTHpSRE9VRm5UVUpCUVVWRFoyZEZRVkZNZUc5NmQySnhTMU5tY0RGRldtNURhM2xLYzFKWmJUZFRWMUl3UkhaYWVGbFVhVmQwUVZGYWNVZHhYRzQxT0drM1RrbE9OalZaWWs0MmVXYzRhbmgyVWxsVlJEWnBTREowVnpBclJFRnpNVk0xZEVKSWJUVlVkMjVRVmtOM05GRm9iMHAyVGxRNVZVZDRNMFpqWEc0d2VFdzRVVWwwYUU0eVJERk1TMHRKUkdoWGJYQXZLMk5oY2tKVloyeFBjRFJwWWpCT1JUSXdaVmxQUm5wWE5VOWxaM1ZCSzBWVE5GTnplR1YyWVhGdVhHNW1iRFpEWVc5VmIxcEtSR0UyUlZCTWEyVjJkME5XT1daU1prOVpVbWhaVWsxamJFTTNVa3hrT0RkRE1FNW9PUzlXS3l0UlZrVjZhbGMwYVZWeVYxSllYRzVtVVZSRE1DdGlhVWh4YmpCR1ZUY3lTbkZVVG5WWk9TOWtVbGhSVjBFMFNWb3diakUxYlVOTFNteDVNRmhZUVZoVlEyczNhMjlrVVhWTmJtTlRNMmN2WEc1dWVXSnphR3BZYlRsQ0t6RTROelJyTXpkV1ZXUllXaTlxV0RKblZYRlpNSGhEU2psRlRXOXRTbEZMUW1kUlJETXZhSEJPY25KUlNXeFBOSE12UVd4VlhHNWxSMDV5ZFd0dFdXeGxhRGxHV21KcFUwNU5ZbFJXYVVSR1RuazFOVkV4ZWpZdlRHdHNlR05hZGk4dldIUXlka1p2TjBoU2MyNHpjRE40T1RVM01HcG5YRzVXU2xoMWJHaHpNREJCZVVabWRIRjBhV2R1VWxabWRFbEtkVkZuVUdWSE1URm1WbkZpZWpkdmRpOU5kV3MyTUVGWWFubHJUbTVzV0VoVVZERk5jekUyWEc1a2NXUjFhSFZ2YnpGbGJXUXpSMlZQUjFSSVNsSklhM1JDZDB0Q1oxRkVkVkJqYUcxdFRFc3dhelJsZEZSYVdXRkxOVXN2U0dka09XUTVjazlRT1dKUlhHNTNlbGszTjNRdlRHODVjR1phZDFrd1EySkdXV1ZWV1hCc1JFeDFTMEZTYWpkV1JsQkxPRXBaZHl0V0swMXBZVkJCYlVkSFdHWmpiSE5ZVGl0NGVHNVVYRzR3VEVoR2JHeGtWMFowYVhCb1lWQk9Sa0o2V0hoNE9VeDFhMmwzU0V0TGVHOW1WVFpHUWl0NmJtNUNSR3d4UmxOQmJFdGFWRFptWkdSWWNEVjJNMWhRWEc0eVV6TXlRa2x5TTBkM1MwSm5RWFJ0ZEd0VVpVSkZOMnR6Wmt0R1pqbFNVRmRLY2t0VVRHNXJTVzVWYkhWbVRXSlZRVVpSVmtGS2NYZG9PRlo0WTBkUVhHNXNia2xzT1VKNmREZzVRWGxGV2xaaWFXdENUM2xZVlc5SFpWWmpUaXRwUVZkM2FFZENSMmQzVEVoTmVYVjBSVUp4UzFCclNsSktWRWd5WmxGRlNVWjNYRzV1WTBSUU4yNDVOakkyTlVoblkzVnFhVmgzZGs5UVRHeFdPWEo1UVM5d1pWaERTVGQwTmxrMk9USjFXR2d6WkVRNU1Fd3JhaXRsWmtGdlIwRkZObkZvWEc0cmJWbHphV3dyVEZkaVJVZzNVVEJtZUdkelUycDZZblp3ZDNJMlJIRXlkWE50TDJKd1draFlSM1l3UlU1Q1QwRjNhemQzYW1OdlowVnBlbGhtTDBFNVhHNVJRVE5oYzNvd2IyMXhlRVpLY0ZWS2RTc3ZVakJTYVNzNFpqUTFhMXBUZFhWRFRHRXZjelZSUVVZMU5UQlNiMUkzTTFsUGFsVXZTbHBHUWxreFpGVkxYRzU1TUhGU0t6RXZaVFJLVjBSTWQxQnRSV0ZZVkhNMlNscEJLMlpqVERsWk4zaDNNVVU0TTFWRFoxbEZRWGxQVFZkcmFYSTRRakpLVEhWclRUSTJXVXhxWEc1ak0xTk5WVUZTWm5SMmIxa3pWVFkyUVZOc2IwbGhZM054VEc1RFEzcFlWSEl2UzJwdWFYUldZbFJIUWtjNGIwWk9URlZaZFVGV1Vta3pOblpxYTNsWVhHNXJZMVpWVVZCWWFIbGtSRk5pVW1STlZrdEpOblJ3Wkc1a01HRkVjRlZwVGtkMWMwaENZV3g2UzBSaFVqZFdXbUpKWVVObE1qWlRXblJNVERoWE0zZEhYRzVTWWsxbFIwY3dURTFtYUhWR01rVlBhSE14VDI1M1NUMWNiaTB0TFMwdFJVNUVJRkJTU1ZaQlZFVWdTMFZaTFMwdExTMWNiaUlzSUNKamJHbGxiblJmWlcxaGFXd2lPaUFpWTI5dVkyOTFjbk5sTFdOcFFHTm1MV0oxYVd4a0xYTmxjblpwWTJVdFpHVjJMVEl4T1RreE15NXBZVzB1WjNObGNuWnBZMlZoWTJOdmRXNTBMbU52YlNJc0lDSmpiR2xsYm5SZmFXUWlPaUFpTVRBMU56UTJOVFUxT1RRek16QXpOVGMzTlRnMUlpd2dJbUYxZEdoZmRYSnBJam9nSW1oMGRIQnpPaTh2WVdOamIzVnVkSE11WjI5dloyeGxMbU52YlM5dkwyOWhkWFJvTWk5aGRYUm9JaXdnSW5SdmEyVnVYM1Z5YVNJNklDSm9kSFJ3Y3pvdkwyOWhkWFJvTWk1bmIyOW5iR1ZoY0dsekxtTnZiUzkwYjJ0bGJpSXNJQ0poZFhSb1gzQnliM1pwWkdWeVgzZzFNRGxmWTJWeWRGOTFjbXdpT2lBaWFIUjBjSE02THk5M2QzY3VaMjl2WjJ4bFlYQnBjeTVqYjIwdmIyRjFkR2d5TDNZeEwyTmxjblJ6SWl3Z0ltTnNhV1Z1ZEY5NE5UQTVYMk5sY25SZmRYSnNJam9nSW1oMGRIQnpPaTh2ZDNkM0xtZHZiMmRzWldGd2FYTXVZMjl0TDNKdlltOTBMM1l4TDIxbGRHRmtZWFJoTDNnMU1Ea3ZZMjl1WTI5MWNuTmxMV05wSlRRd1kyWXRZblZwYkdRdGMyVnlkbWxqWlMxa1pYWXRNakU1T1RFekxtbGhiUzVuYzJWeWRtbGpaV0ZqWTI5MWJuUXVZMjl0SWlCOSIsInBhc3N3b3JkIjoieyBcInR5cGVcIjogXCJzZXJ2aWNlX2FjY291bnRcIiwgXCJwcm9qZWN0X2lkXCI6IFwiY2YtYnVpbGQtc2VydmljZS1kZXYtMjE5OTEzXCIsIFwicHJpdmF0ZV9rZXlfaWRcIjogXCIxZmU0YWVmMjRhNGNiNTg0OGUwZWYxZWVlYTVjM2NiMDdlMTk3NWRhXCIsIFwicHJpdmF0ZV9rZXlcIjogXCItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cXG5NSUlFdlFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLY3dnZ1NqQWdFQUFvSUJBUURteWhZaVpLVXBpc0h2XFxuVWVxbHZZUi84dmNzMVp2bDE2dXZDenlJSGgvdGlRSzFPZ3NFMEdFTXZQQmpkZ1NrWXYzKzVCTlpnVGRscUVWd1xcblgzR3Qyb1J1K0NKemh4QkRLY2VjUVRNelVsbzM5TTZxcFR4SFdlcVFqYWw4a0N1dUk3QkJYemVjUHNSUEM3NFNcXG5lamYvNmtsU3JaZERPTTF3bmxvS3NOYkpXWnRZRkpPRHJIVzEwRjJmV1d3dFZjb29XUzRVZ3AyYzhuNElrMytNXFxuQlo1WWVRV0ZVdWFJNmo4M0Fpd243aExpODdTWElwUlhaM255a0p6ME5WOUlrVlpFZ0ErczRyTUc3WkJhSnlWeVxcbnFaMGpoL25DeUpmd1YybkVoVStRWWkxbmtUeWpNMThNdU1jdEgyTXcwOGIzS0hVOUZZendhcEtjbjVFekpqU01cXG52d3VFLzRDOUFnTUJBQUVDZ2dFQVFMeG96d2JxS1NmcDFFWm5Da3lKc1JZbTdTV1IwRHZaeFlUaVd0QVFacUdxXFxuNThpN05JTjY1WWJONnlnOGp4dlJZVUQ2aUgydFcwK0RBczFTNXRCSG01VHduUFZDdzRRaG9Kdk5UOVVHeDNGY1xcbjB4TDhRSXRoTjJEMUxLS0lEaFdtcC8rY2FyQlVnbE9wNGliME5FMjBlWU9Gelc1T2VndUErRVM0U3N4ZXZhcW5cXG5mbDZDYW9Vb1pKRGE2RVBMa2V2d0NWOWZSZk9ZUmhZUk1jbEM3UkxkODdDME5oOS9WKytRVkV6alc0aVVyV1JYXFxuZlFUQzArYmlIcW4wRlU3MkpxVE51WTkvZFJYUVdBNElaMG4xNW1DS0pseTBYWEFYVUNrN2tvZFF1TW5jUzNnL1xcbm55YnNoalhtOUIrMTg3NGszN1ZVZFhaL2pYMmdVcVkweENKOUVNb21KUUtCZ1FEMy9ocE5yclFJbE80cy9BbFVcXG5lR05ydWttWWxlaDlGWmJpU05NYlRWaURGTnk1NVExejYvTGtseGNadi8vWHQydkZvN0hSc24zcDN4OTU3MGpnXFxuVkpYdWxoczAwQXlGZnRxdGlnblJWZnRJSnVRZ1BlRzExZlZxYno3b3YvTXVrNjBBWGp5a05ubFhIVFQxTXMxNlxcbmRxZHVodW9vMWVtZDNHZU9HVEhKUkhrdEJ3S0JnUUR1UGNobW1MSzBrNGV0VFpZYUs1Sy9IZ2Q5ZDlyT1A5YlFcXG53elk3N3QvTG85cGZad1kwQ2JGWWVVWXBsREx1S0FSajdWRlBLOEpZdytWK01pYVBBbUdHWGZjbHNYTit4eG5UXFxuMExIRmxsZFdGdGlwaGFQTkZCelh4eDlMdWtpd0hLS3hvZlU2RkIrem5uQkRsMUZTQWxLWlQ2ZmRkWHA1djNYUFxcbjJTMzJCSXIzR3dLQmdBdG10a1RlQkU3a3NmS0ZmOVJQV0pyS1RMbmtJblVsdWZNYlVBRlFWQUpxd2g4VnhjR1BcXG5sbklsOUJ6dDg5QXlFWlZiaWtCT3lYVW9HZVZjTitpQVd3aEdCR2d3TEhNeXV0RUJxS1BrSlJKVEgyZlFFSUZ3XFxubmNEUDduOTYyNjVIZ2N1amlYd3ZPUExsVjlyeUEvcGVYQ0k3dDZZNjkydVhoM2REOTBMK2orZWZBb0dBRTZxaFxcbittWXNpbCtMV2JFSDdRMGZ4Z3NTanpidnB3cjZEcTJ1c20vYnBaSFhHdjBFTkJPQXdrN3dqY29nRWl6WGYvQTlcXG5RQTNhc3owb21xeEZKcFVKdSsvUjBSaSs4ZjQ1a1pTdXVDTGEvczVRQUY1NTBSb1I3M1lPalUvSlpGQlkxZFVLXFxueTBxUisxL2U0SldETHdQbUVhWFRzNkpaQStmY0w5WTd4dzFFODNVQ2dZRUF5T01Xa2lyOEIySkx1a00yNllMalxcbmMzU01VQVJmdHZvWTNVNjZBU2xvSWFjc3FMbkNDelhUci9Lam5pdFZiVEdCRzhvRk5MVVl1QVZSaTM2dmpreVhcXG5rY1ZVUVBYaHlkRFNiUmRNVktJNnRwZG5kMGFEcFVpTkd1c0hCYWx6S0RhUjdWWmJJYUNlMjZTWnRMTDhXM3dHXFxuUmJNZUdHMExNZmh1RjJFT2hzMU9ud0k9XFxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxcblwiLCBcImNsaWVudF9lbWFpbFwiOiBcImNvbmNvdXJzZS1jaUBjZi1idWlsZC1zZXJ2aWNlLWRldi0yMTk5MTMuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb21cIiwgXCJjbGllbnRfaWRcIjogXCIxMDU3NDY1NTU5NDMzMDM1Nzc1ODVcIiwgXCJhdXRoX3VyaVwiOiBcImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoXCIsIFwidG9rZW5fdXJpXCI6IFwiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW5cIiwgXCJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmxcIjogXCJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHNcIiwgXCJjbGllbnRfeDUwOV9jZXJ0X3VybFwiOiBcImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvY29uY291cnNlLWNpJTQwY2YtYnVpbGQtc2VydmljZS1kZXYtMjE5OTEzLmlhbS5nc2VydmljZWFjY291bnQuY29tXCIgfSIsInVzZXJuYW1lIjoiX2pzb25fa2V5In19fQ==
kind: Secret
metadata:
  name: secret
  namespace: kpack
type: kubernetes.io/dockerconfigjson
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: builds.build.pivotal.io
spec:
  group: build.pivotal.io
  version: v1alpha1
  names:
    kind: Build
    singular: build
    plural: builds
    shortNames:
    - cnbbuild
    - cnbbuilds
    - bld
    categories:
    - kpack
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Image
    type: string
    JSONPath: .status.latestImage
  - name: Succeeded
    type: string
    JSONPath: .status.conditions[?(@.type=="Succeeded")].status
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: builders.build.pivotal.io
spec:
  group: build.pivotal.io
  version: v1alpha1
  names:
    kind: Builder
    singular: builder
    plural: builders
    shortNames:
    - cnbbuilder
    - cnbbuilders
    - bldr
    categories:
    - kpack
  scope: Namespaced
  subresources:
    status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterbuilders.build.pivotal.io
spec:
  group: build.pivotal.io
  version: v1alpha1
  names:
    kind: ClusterBuilder
    singular: clusterbuilder
    plural: clusterbuilders
    shortNames:
    - clstbldr
    categories:
    - kpack
  scope: Cluster
  subresources:
    status: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kpack-controller-admin
rules:
- apiGroups:
  - build.pivotal.io
  resources:
  - builds
  - builds/status
  - builds/finalizers
  - images
  - images/status
  - images/finalizers
  - builders
  - builders/status
  - clusterbuilders
  - clusterbuilders/status
  - sourceresolvers
  - sourceresolvers/status
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - pods
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - watch
- apiGroups:
  - experimental.kpack.pivotal.io
  resources:
  - custombuilders
  - custombuilders/status
  - customclusterbuilders
  - customclusterbuilders/status
  - stores
  - stores/status
  - stacks
  - stacks/status
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kpack-webhook-admin
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/finalizers
  verbs:
  - get
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kpack-controller-admin
subjects:
- kind: ServiceAccount
  name: controller
  namespace: kpack
roleRef:
  kind: ClusterRole
  name: kpack-controller-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kpack-webhook-admin
subjects:
- kind: ServiceAccount
  name: webhook
  namespace: kpack
roleRef:
  kind: ClusterRole
  name: kpack-webhook-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpack-controller
  namespace: kpack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpack-controller
  template:
    metadata:
      labels:
        app: kpack-controller
        version: dev
    spec:
      serviceAccountName: controller
      containers:
      - name: controller
        image: kpack/controller@sha256:78cae5f924f298d56636270b893e0906c7515f9b6103618ce35f0e3ed18f5f0c
        env:
        - name: BUILD_INIT_IMAGE
          value: kpack/build-init@sha256:7d791d355a9d5764d5d90b88af959adbd4f86aa54e308c575417892536b4730f
        - name: REBASE_IMAGE
          value: kpack/rebase@sha256:0fbcaa8ac762c9855b5e481fba4ba5f94b81c49dcce4e98d1181afd0ec6ea8e0
        - name: COMPLETION_IMAGE
          value: kpack/completion@sha256:c68db68a4696223b35013a3b16318cacfca32f336ef1ce8716a41c68f6ee074f
        - name: LIFECYCLE_IMAGE
          value: kpack/lifecycle@sha256:b74697c40c03d73a969d765bece1dcfa739c703f416e683a23fa02c9e0ed700d
        - name: CREDENTIAL_PROVIDER_SECRET_PATH
          value: /var/kpack/credentials
        volumeMounts:
        - name: credentials
          mountPath: /var/kpack/credentials
          readOnly: true
      volumes:
      - name: credentials
        secret:
          secretName: secret

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: custombuilders.experimental.kpack.pivotal.io
spec:
  group: experimental.kpack.pivotal.io
  version: v1alpha1
  names:
    kind: CustomBuilder
    singular: custombuilder
    plural: custombuilders
    shortNames:
    - custmbldr
    categories:
    - kpack
  scope: Namespaced
  subresources:
    status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: customclusterbuilders.experimental.kpack.pivotal.io
spec:
  group: experimental.kpack.pivotal.io
  version: v1alpha1
  names:
    kind: CustomClusterBuilder
    singular: customclusterbuilder
    plural: customclusterbuilders
    shortNames:
    - ccb
    categories:
    - kpack
  scope: Cluster
  subresources:
    status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: images.build.pivotal.io
spec:
  group: build.pivotal.io
  version: v1alpha1
  names:
    kind: Image
    singular: image
    plural: images
    shortNames:
    - cnbimage
    - cnbimages
    categories:
    - kpack
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: LatestImage
    type: string
    JSONPath: .status.latestImage
  - name: Ready
    type: string
    JSONPath: .status.conditions[?(@.type=="Ready")].status
---
apiVersion: v1
kind: Service
metadata:
  name: kpack-webhook
  namespace: kpack
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    role: webhook
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: kpack
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook
  namespace: kpack
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sourceresolvers.build.pivotal.io
spec:
  group: build.pivotal.io
  version: v1alpha1
  names:
    kind: SourceResolver
    singular: sourceresolver
    plural: sourceresolvers
    categories:
    - kpack
  scope: Namespaced
  subresources:
    status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: stacks.experimental.kpack.pivotal.io
spec:
  group: experimental.kpack.pivotal.io
  version: v1alpha1
  names:
    kind: Stack
    singular: stack
    plural: stacks
    categories:
    - kpack
  scope: Cluster
  subresources:
    status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: stores.experimental.kpack.pivotal.io
spec:
  group: experimental.kpack.pivotal.io
  version: v1alpha1
  names:
    kind: Store
    singular: store
    plural: stores
    categories:
    - kpack
  scope: Cluster
  subresources:
    status: {}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: resource.webhook.kpack.pivotal.io
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: kpack-webhook
      namespace: kpack
  failurePolicy: Fail
  name: resource.webhook.kpack.pivotal.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpack-webhook
  namespace: kpack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpack-webhook
  template:
    metadata:
      labels:
        app: kpack-webhook
        role: webhook
        version: dev
    spec:
      serviceAccountName: webhook
      containers:
      - name: webhook
        image: kpack/webhook@sha256:684a64444416cb2a1e29dd1310149b6daa856f421aceffc1f3211d9820576292
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
